internal/command/commands/service.go
=> platform added to service deploy help section

app/app.go, internal/command/commands/env.go, internal/command/commands/service.go
- makes synchronous logging default for supported commands i.e. remove the use of `-tail` argument to access synchronous logs.
=> feat: make synchronous logs default for supporting commands

app/app.go, internal/backend/service.go, internal/command/commands/service.go
=> feat: add d11-config-store-namespace parameter in deploy service

internal/command/command_catalog.go, internal/command/commands/application_template.go, internal/command/commands/command.go
Add new verb `generate` to generate resources for `application-template`.
sample command :
```
$odin generate application-template
$odin generate application-template --service=<name of service>
```
=> feat: add generate application-template command

internal/backend/serviceset.go, internal/command/commands/serviceset.go
=> taking config store branch name input for service-set deploy

internal/command/commands/application_template.go
- Odin init command no longer asks for language, language-version. Since, both these values are recorded from service-def file
=> fix: update odin init app-spec file

main.go
Shows warning message when not using latest version
=> feat: odin update alert message

main.go
=> feat: odin update alert message (#91)

main.go
=> fix: odin update alert message log type

main.go
=> fix: nil ptr refrence

internal/backend/auth.go, internal/backend/client.go, internal/backend/componentType.go, internal/backend/env.go, internal/backend/label.go, internal/backend/service.go, internal/backend/serviceset.go, pkg/sse/stream_events.go
=> Retries added to the odin backend APIs

api/service/service.go, internal/command/commands/env.go, internal/command/commands/service.go
Remove `--team` input at team create
=> fix: remove team input at env create

internal/command/commands/configure.go
=> feat: use access key, secret access key from env variable

main.go
=> fix: latest version check response status code

api/service/service.go, internal/backend/service.go, internal/command/commands/label.go, internal/command/commands/service.go
=> Made create sync and removed mature commands

main.go
=> fix: latest version check response status code error msg

internal/command/commands/serviceset.go
=> changed .yaml to .json

internal/backend/service.go, internal/command/command_catalog.go, internal/command/commands/command.go, internal/command/commands/service.go
=> Merged create and deploy

internal/command/commands/service.go
=> removed rebuild flag from the create service command

internal/command/commands/application_template.go
=> Added log messages

internal/command/commands/service.go, pkg/utils/utils.go
=> chore: warning when ignoring provisioning files

internal/command/commands/service.go
=> message changes in case of temp service deployment

internal/backend/service.go, internal/command/commands/service.go
=> Dead code removed

internal/command/commands/service.go
=> added --file in deploy service help command

internal/command/commands/componentType.go
=> chore: display exposed component config table

api/configuration/configuration.go, internal/backend/env.go, internal/command/command_catalog.go, internal/command/commands/command.go, internal/command/commands/env.go, internal/command/commands/service.go, internal/command/commands/serviceset.go, pkg/utils/utils.go
Details of the PR: https://dream11.atlassian.net/browse/DEVX-2489
Automation job link: https://cistag-internal.dream11.com/job/Devx-Automation/847/console
=> Default env devx 2489

app/app.go
=> chore: bump version to 1.2.0-beta

api/configuration/configuration.go, app/app.go, internal/backend/service.go, internal/command/command_catalog.go, internal/command/commands/command.go, internal/command/commands/componentType.go, internal/command/commands/env.go, internal/command/commands/service.go, internal/command/commands/serviceset.go, pkg/utils/utils.go
=> Release 1.2.0-beta

internal/command/commands/env.go
Details of pr : https://dream11.atlassian.net/browse/DEVX-2509
=> Env name input devx 2509

internal/command/commands/env.go
Details of this pR: https://dream11.atlassian.net/browse/DEVX-2564
=> Devx 2564 reenter env name

api/component/component.go, api/envtype/envtype.go, api/service/service.go, app/app.go, internal/backend/envtype.go, internal/command/command_catalog.go, internal/command/commands/componentType.go, internal/command/commands/env.go, internal/command/commands/envtype.go, internal/command/commands/service.go
=> Release odin version 1.2.0-beta.2

internal/command/commands/env.go
=> add name in create env

internal/command/commands/env.go
➜  odin git:(development*)odin list env
Listing all environment(s)
NAME     | TEAM | ENV TYPE | STATE   | ACCOUNT  
-----------+------+----------+---------+----------
dev-7892 | sdet | dev      | RUNNING | staging  
dev-7891 | sdet | load     | RUNNING | staging
=> remove-dev-default-filter

api/service/service.go, internal/backend/service.go, internal/command/commands/service.go
Requirement: https://dream11.atlassian.net/browse/DEVX-2572
=> Config diff

internal/backend/env.go, internal/command/command_catalog.go, internal/command/commands/command.go, internal/command/commands/env.go
1.2.0-beta.2
added update env command for updating an env.
https://dream11.atlassian.net/browse/DEVX-2687
=> added new command for updating an env

app/app.go
=> chore: bump version to 1.2.0-beta.3

app/app.go, go.mod, go.sum, internal/backend/serviceset.go, internal/command/commands/serviceset.go, internal/ui/formatting.go, internal/ui/multi_spinner.go, pkg/sse/stream_events.go
Stream service-set `deploy` and `undeploy` actions
https://github.com/dream11/playgroundV2/pull/334
=> Stream serviceset actions

internal/command/commands/serviceset.go
=> corrected output message for odin list service-set command

app/app.go, go.mod, go.sum, internal/backend/serviceset.go, internal/command/commands/serviceset.go, internal/ui/formatting.go, internal/ui/multi_spinner.go, pkg/sse/stream_events.go
=> Odin release DX-665

internal/command/commands/service.go
Signed-off-by: Akshay Patidar <akshaypatidar1999@gmail.com>
=> DX-733: labels in list service output

.github/workflows/go-lint.yaml, app/app.go, internal/backend/client.go, internal/command/commands/env.go, internal/command/commands/label.go, internal/command/commands/service.go, internal/constant/const.go, pkg/dir/dir.go, pkg/request/request.go
=> Release version 1.2.1

api/environment/env.go, internal/command/commands/env.go
=> Dx 226 service status fix

internal/command/commands/env.go, internal/command/commands/service.go
Modified error messages as mentioned in column 9, 15, 17 and of this file:
https://dream11-my.sharepoint.com/:x:/g/personal/sharmistha_roy_dream11_onmicrosoft_com/ET5OfZ4KtRFDr6BCXuvbs_gBmFA4TJFmvJSvQMZpB4bqGg?rtime=M3Sly-fR2kg
=> Modified error messages

api/environment/env.go, internal/command/commands/env.go
=> Dx 1217 show jenkins url

app/app.go
=> update odin version

app/app.go, internal/backend/env.go, internal/command/commands/env.go
=> changes to odin list env command

api/environment/env.go, internal/backend/serviceset.go, internal/command/commands/env.go, internal/command/commands/serviceset.go
=> Release 20230104

app/app.go, internal/backend/env.go, internal/command/commands/env.go, internal/command/commands/service.go, pkg/table/table.go, pkg/utils/utils.go
=> parallel execution for getting status of services in an environment

internal/backend/env.go
=> remove match status code func

api/component/component.go, api/componenttype/componenttype.go, api/operation/operation.go, api/service/service.go, app/app.go, internal/backend/component.go, internal/backend/componentType.go, internal/backend/env.go, internal/backend/operation.go, internal/command/command_catalog.go, internal/command/commands/command.go, internal/command/commands/component.go, internal/command/commands/env.go, internal/command/commands/operation.go, internal/command/commands/service.go, pkg/table/table.go, pkg/utils/utils.go
=> Release 20230309

api/component/component.go, api/componenttype/componenttype.go, api/operation/operation.go, api/service/service.go, app/app.go, internal/backend/component.go, internal/backend/componentType.go, internal/backend/env.go, internal/backend/operation.go, internal/command/command_catalog.go, internal/command/commands/command.go, internal/command/commands/component.go, internal/command/commands/env.go, internal/command/commands/operation.go, internal/command/commands/service.go, pkg/table/table.go, pkg/utils/utils.go
=> Odin status env fix

api/service/service.go, app/app.go, internal/backend/operation.go, internal/backend/service.go, internal/command/command_catalog.go, internal/command/commands/operation.go, internal/command/commands/service.go
=> Operate service

internal/command/commands/service.go
=> removed performing validation log

api/envtype/envtype.go, internal/backend/envtype.go, internal/command/commands/component.go, internal/command/commands/service.go
=> added consent logs for operate commands

internal/command/commands/component.go, internal/command/commands/service.go
=> chore: type env name in strict type operations

api/envtype/envtype.go, api/service/service.go, app/app.go, internal/backend/envtype.go, internal/backend/operation.go, internal/backend/service.go, internal/command/command_catalog.go, internal/command/commands/component.go, internal/command/commands/operation.go, internal/command/commands/service.go
=> Development to main

.github/workflows/go-lint.yaml, api/component/component.go, internal/backend/component.go, internal/command/commands/component.go
=> Operate diff and --file flag

.github/workflows/release.yaml, api/environment/env.go, app/app.go, internal/command/commands/env.go
=> Multi account support for env creation

.github/workflows/release.yaml
=> Release 20230613

.github/workflows/release.yaml
=> Fix for release

app/app.go, internal/command/commands/env.go
=> no hyphen at the end of env name

.github/workflows/go-lint.yaml, .github/workflows/release.yaml, app/app.go, internal/command/commands/component.go, internal/command/commands/env.go
=> Develop to Main

api/environment/env.go, app/app.go, internal/backend/env.go, internal/backend/operation.go, internal/command/command_catalog.go, internal/command/commands/env.go, internal/command/commands/operation.go, internal/command/commands/service.go, internal/command/commands/serviceset.go
=> environment operations

internal/command/commands/operation.go
=> fix the issue when entity is none

cmd/configure/configure.go
=> feat: enable insecure by default

internal/service/client.go, internal/service/environment.go, pkg/util/util.go
=> fix: grpc connection for insecure

cmd/delete/environment.go
=> Fix: Add validation for name flag in delete env command

cmd/deploy/deploy.go, cmd/deploy/service.go, go.mod, go.sum, internal/service/environment.go, internal/service/service.go, main.go, pkg/util/file.go
=> feat: init deploy on cobra cli

cmd/undeploy/service.go
=> Fix: undeploy log

cmd/set/profile.go, cmd/set/set.go, internal/service/service.go, main.go, pkg/config/config.go
=> add set profile command

.gitignore, internal/service/client.go, pkg/config/config.go
=> fix issue in odin configure

api/environment/env.go, app/app.go
=> Clustername in describe env

api/environment/env.go, app/app.go
=> Clustername in describe env (#242)

api/environment/env.go, app/app.go
=> Cluster name in describe env

proto/dream11/od/dto/v1/service.proto
=> Updated proto

cmd/create/environment.go, cmd/delete/environment.go, cmd/deploy/service-set.go, cmd/deploy/service.go, cmd/list/environment.go, cmd/operate/component.go, cmd/operate/service.go, cmd/set/env.go, cmd/undeploy/service.go, internal/service/service.go, pkg/config/config.go
=> added set env cmd and use default env when running

cmd/describe/environment.go
=> fix: describe env command

internal/service/component.go, internal/service/service.go, pkg/util/util.go
=> fix: operate service response

cmd/describe/environment.go
=> fix: describe output

README.md, internal/ui/logger.go, main.go, pkg/constant/constant.go
=> feat: enable debug level logs support

internal/ui/logger.go, pkg/util/util.go
=> fix: env var lookup for logger

cmd/describe/environment.go
=> added status of service in output

cmd/deploy/service-set.go
=> added changes

switch.py
=> fix: old odin path init

switch.py
=> chore: minor fixes
